import { RoleStatKey } from "@/lib/types";

// Custom labels for each stat
export const statLabels: Record<RoleStatKey, string> = {
  wins: "Win Rate",
  kills: "Kills",
  deaths: "Deaths",
  assists: "Assists",
  kda: "KDA",
  totalMinionsKilled: "Minions Killed",
  neutralMinionsKilled: "Neutral Minions Killed",
  totalCS: "Total CS",
  csPerMinute: "CS Per Minute",
  goldEarned: "Gold Earned",
  goldPerMinute: "Gold Per Minute",
  totalDamageDealtToChampions: "Total Damage to Champions",
  damagePerMinute: "Damage Per Minute",
  physicalDamageDealtToChampions: "Physical Damage",
  magicDamageDealtToChampions: "Magic Damage",
  trueDamageDealtToChampions: "True Damage",
  visionScore: "Vision Score",
  visionScorePerMinute: "Vision Score Per Minute",
  wardsPlaced: "Wards Placed",
  wardsKilled: "Wards Killed",
  visionWardsBoughtInGame: "Control Wards Bought",
  damageDealtToObjectives: "Damage to Objectives",
  damageDealtToTurrets: "Damage to Turrets",
  totalDamageTaken: "Total Damage Taken",
  damageSelfMitigated: "Damage Self Mitigated",
  totalHeal: "Total Heal",
  timeCCingOthers: "Time CCing Others",
  totalTimeCrowdControlDealt: "Total CC Time",
  teamKills: "Team Kills",
  teamDamage: "Team Damage",
  killParticipation: "Kill Participation",
  damageShare: "Damage Share",
  goldAt10: "Gold @ 10min",
  xpAt10: "XP @ 10min",
  csAt10: "CS @ 10min",
  levelAt10: "Level @ 10min",
  goldDiffAt10: "Gold Diff @ 10min",
  xpDiffAt10: "XP Diff @ 10min",
  csDiffAt10: "CS Diff @ 10min",
  goldAt15: "Gold @ 15min",
  xpAt15: "XP @ 15min",
  csAt15: "CS @ 15min",
  levelAt15: "Level @ 15min",
  goldDiffAt15: "Gold Diff @ 15min",
  xpDiffAt15: "XP Diff @ 15min",
  csDiffAt15: "CS Diff @ 15min",
  goldAt20: "Gold @ 20min",
  xpAt20: "XP @ 20min",
  csAt20: "CS @ 20min",
  levelAt20: "Level @ 20min",
  goldDiffAt20: "Gold Diff @ 20min",
  xpDiffAt20: "XP Diff @ 20min",
  csDiffAt20: "CS Diff @ 20min",
  soloKills: "Solo Kills",
  firstBlood: "First Blood Participation",
  firstBloodKill: "First Blood Kill Participation",
  firstBloodAssist: "First Blood Assist Participation",
  doubleKills: "Double Kills",
  tripleKills: "Triple Kills",
  quadraKills: "Quadra Kills",
  pentaKills: "Penta Kills",
  turretKills: "Turret Kills",
  inhibitorKills: "Inhibitor Kills",
  firstTowerKill: "First Tower Kills",
  firstTowerAssist: "First Tower Assists",
  killsAndAssistsPre15: "Kills & Assists Pre-15",
  teamKillsPre15: "Team Kills Pre-15",
  earlyGameKP: "Early Game Kill Participation",
  damagePerDeath: "Damage Per Death",
  damagePerGold: "Damage Per Gold",
  objectiveControlRate: "Objective Control Rate",
  roamsSuccessful: "Successful Roams",
  score: "Performance Score",
};

// Stat descriptions indicating whether it's an average or total
export const statDescriptions: Record<RoleStatKey, "average" | "total"> = {
  wins: "average",
  kills: "average",
  deaths: "average",
  assists: "average",
  kda: "average",
  totalMinionsKilled: "average",
  neutralMinionsKilled: "average",
  totalCS: "average",
  csPerMinute: "average",
  goldEarned: "average",
  goldPerMinute: "average",
  totalDamageDealtToChampions: "average",
  damagePerMinute: "average",
  physicalDamageDealtToChampions: "average",
  magicDamageDealtToChampions: "average",
  trueDamageDealtToChampions: "average",
  visionScore: "average",
  visionScorePerMinute: "average",
  wardsPlaced: "average",
  wardsKilled: "average",
  visionWardsBoughtInGame: "average",
  damageDealtToObjectives: "average",
  damageDealtToTurrets: "average",
  totalDamageTaken: "average",
  damageSelfMitigated: "average",
  totalHeal: "average",
  timeCCingOthers: "average",
  totalTimeCrowdControlDealt: "average",
  teamKills: "average",
  teamDamage: "average",
  killParticipation: "average",
  damageShare: "average",
  goldAt10: "average",
  xpAt10: "average",
  csAt10: "average",
  levelAt10: "average",
  goldDiffAt10: "average",
  xpDiffAt10: "average",
  csDiffAt10: "average",
  goldAt15: "average",
  xpAt15: "average",
  csAt15: "average",
  levelAt15: "average",
  goldDiffAt15: "average",
  xpDiffAt15: "average",
  csDiffAt15: "average",
  goldAt20: "average",
  xpAt20: "average",
  csAt20: "average",
  levelAt20: "average",
  goldDiffAt20: "average",
  xpDiffAt20: "average",
  csDiffAt20: "average",
  soloKills: "average",
  firstBlood: "average",
  firstBloodKill: "average",
  firstBloodAssist: "average",
  doubleKills: "total",
  tripleKills: "total",
  quadraKills: "total",
  pentaKills: "total",
  turretKills: "average",
  inhibitorKills: "average",
  firstTowerKill: "average",
  firstTowerAssist: "average",
  killsAndAssistsPre15: "average",
  teamKillsPre15: "average",
  earlyGameKP: "average",
  damagePerDeath: "average",
  damagePerGold: "average",
  objectiveControlRate: "average",
  roamsSuccessful: "average",
  score: "average",
};

// Helper function to get description text
export const getStatDescription = (stat: RoleStatKey): string => {
  const type = statDescriptions[stat];
  return type === "average" ? "Average across games" : "Total sum across games";
};

// Stat categories
export const statCategories: Array<{
  label: string;
  stats: RoleStatKey[];
}> = [
  {
    label: "Performance",
    stats: ["wins", "score", "kda"],
  },
  {
    label: "Combat",
    stats: [
      "kills",
      "deaths",
      "assists",
      "soloKills",
      "firstBlood",
      "firstBloodKill",
      "firstBloodAssist",
      "doubleKills",
      "tripleKills",
      "quadraKills",
      "pentaKills",
    ],
  },
  {
    label: "Damage",
    stats: [
      "totalDamageDealtToChampions",
      "damagePerMinute",
      "physicalDamageDealtToChampions",
      "magicDamageDealtToChampions",
      "trueDamageDealtToChampions",
      "damageShare",
      "damagePerDeath",
      "damagePerGold",
    ],
  },
  {
    label: "Economy",
    stats: [
      "goldEarned",
      "goldPerMinute",
      "totalCS",
      "csPerMinute",
      "totalMinionsKilled",
      "neutralMinionsKilled",
    ],
  },
  {
    label: "Vision",
    stats: [
      "visionScore",
      "visionScorePerMinute",
      "wardsPlaced",
      "wardsKilled",
      "visionWardsBoughtInGame",
    ],
  },
  {
    label: "Objectives",
    stats: [
      "damageDealtToObjectives",
      "damageDealtToTurrets",
      "turretKills",
      "inhibitorKills",
      "firstTowerKill",
      "firstTowerAssist",
    ],
  },
  {
    label: "Team Contribution",
    stats: [
      "killParticipation",
      "teamKills",
      "teamDamage",
      "earlyGameKP",
      "killsAndAssistsPre15",
      "teamKillsPre15",
    ],
  },
  {
    label: "Early Game (10min)",
    stats: [
      "goldAt10",
      "xpAt10",
      "csAt10",
      "levelAt10",
      "goldDiffAt10",
      "xpDiffAt10",
      "csDiffAt10",
    ],
  },
  {
    label: "Mid Game (15min)",
    stats: [
      "goldAt15",
      "xpAt15",
      "csAt15",
      "levelAt15",
      "goldDiffAt15",
      "xpDiffAt15",
      "csDiffAt15",
    ],
  },
  {
    label: "Mid-Late Game (20min)",
    stats: [
      "goldAt20",
      "xpAt20",
      "csAt20",
      "levelAt20",
      "goldDiffAt20",
      "xpDiffAt20",
      "csDiffAt20",
    ],
  },
  {
    label: "Survivability",
    stats: ["totalDamageTaken", "damageSelfMitigated", "totalHeal"],
  },
  {
    label: "Utility",
    stats: ["timeCCingOthers", "totalTimeCrowdControlDealt"],
  },
  {
    label: "Advanced",
    stats: ["objectiveControlRate", "roamsSuccessful"],
  },
];
