export interface ChampionData {
  rank: number;
  championId: number;
  champion: string;
  games: number;
  wins: number;
  losses: number;
  winRate: string;
  kda: string;
  avgDamage: string;
}

export interface StandoutChampion {
  championId: number;
  championName: string;
  stat: string;
  value: string;
  gamesPlayed: number;
  winRate: string;
}

// Mocked standout champions data
export const standoutChampions: StandoutChampion[] = [
  {
    championId: 222,
    championName: "Jinx",
    stat: "Most Wins (Last 20)",
    value: "75%",
    gamesPlayed: 24,
    winRate: "75%",
  },
  {
    championId: 64,
    championName: "Lee Sin",
    stat: "Most Played (Last 20)",
    value: "48",
    gamesPlayed: 48,
    winRate: "62.5%",
  },
  {
    championId: 412,
    championName: "Thresh",
    stat: "Most Banned (Last 20)",
    value: "4.8",
    gamesPlayed: 32,
    winRate: "68.8%",
  },
  {
    championId: 157,
    championName: "Yasuo",
    stat: "Most Losses (Last 20)",
    value: "28.5k",
    gamesPlayed: 36,
    winRate: "55.6%",
  },
];

// Mocked table data
export const championTableData: ChampionData[] = [
  {
    rank: 1,
    championId: 222,
    champion: "Jinx",
    games: 24,
    wins: 18,
    losses: 6,
    winRate: "75.0%",
    kda: "4.2",
    avgDamage: "24.5k",
  },
  {
    rank: 2,
    championId: 64,
    champion: "Lee Sin",
    games: 48,
    wins: 30,
    losses: 18,
    winRate: "62.5%",
    kda: "3.8",
    avgDamage: "18.2k",
  },
  {
    rank: 3,
    championId: 412,
    champion: "Thresh",
    games: 32,
    wins: 22,
    losses: 10,
    winRate: "68.8%",
    kda: "4.8",
    avgDamage: "12.3k",
  },
  {
    rank: 4,
    championId: 157,
    champion: "Yasuo",
    games: 36,
    wins: 20,
    losses: 16,
    winRate: "55.6%",
    kda: "3.5",
    avgDamage: "28.5k",
  },
  {
    rank: 5,
    championId: 99,
    champion: "Lux",
    games: 28,
    wins: 19,
    losses: 9,
    winRate: "67.9%",
    kda: "4.1",
    avgDamage: "22.8k",
  },
  {
    rank: 6,
    championId: 81,
    champion: "Ezreal",
    games: 42,
    wins: 24,
    losses: 18,
    winRate: "57.1%",
    kda: "3.9",
    avgDamage: "26.1k",
  },
  {
    rank: 7,
    championId: 238,
    champion: "Zed",
    games: 25,
    wins: 15,
    losses: 10,
    winRate: "60.0%",
    kda: "4.5",
    avgDamage: "25.3k",
  },
  {
    rank: 8,
    championId: 103,
    champion: "Ahri",
    games: 30,
    wins: 17,
    losses: 13,
    winRate: "56.7%",
    kda: "3.7",
    avgDamage: "21.9k",
  },
  {
    rank: 9,
    championId: 67,
    champion: "Vayne",
    games: 22,
    wins: 13,
    losses: 9,
    winRate: "59.1%",
    kda: "4.0",
    avgDamage: "27.2k",
  },
  {
    rank: 10,
    championId: 498,
    champion: "Xayah",
    games: 19,
    wins: 11,
    losses: 8,
    winRate: "57.9%",
    kda: "3.6",
    avgDamage: "23.8k",
  },
  {
    rank: 11,
    championId: 777,
    champion: "Yone",
    games: 27,
    wins: 14,
    losses: 13,
    winRate: "51.9%",
    kda: "3.2",
    avgDamage: "24.1k",
  },
  {
    rank: 12,
    championId: 555,
    champion: "Pyke",
    games: 20,
    wins: 12,
    losses: 8,
    winRate: "60.0%",
    kda: "4.3",
    avgDamage: "14.5k",
  },
  {
    rank: 13,
    championId: 517,
    champion: "Sylas",
    games: 24,
    wins: 13,
    losses: 11,
    winRate: "54.2%",
    kda: "3.4",
    avgDamage: "20.7k",
  },
  {
    rank: 14,
    championId: 236,
    champion: "Lucian",
    games: 26,
    wins: 15,
    losses: 11,
    winRate: "57.7%",
    kda: "3.8",
    avgDamage: "25.6k",
  },
  {
    rank: 15,
    championId: 84,
    champion: "Akali",
    games: 21,
    wins: 11,
    losses: 10,
    winRate: "52.4%",
    kda: "3.3",
    avgDamage: "22.4k",
  },
  {
    rank: 16,
    championId: 245,
    champion: "Ekko",
    games: 18,
    wins: 10,
    losses: 8,
    winRate: "55.6%",
    kda: "3.5",
    avgDamage: "19.8k",
  },
  {
    rank: 17,
    championId: 91,
    champion: "Talon",
    games: 16,
    wins: 9,
    losses: 7,
    winRate: "56.3%",
    kda: "3.9",
    avgDamage: "21.3k",
  },
  {
    rank: 18,
    championId: 142,
    champion: "Zoe",
    games: 15,
    wins: 8,
    losses: 7,
    winRate: "53.3%",
    kda: "3.1",
    avgDamage: "18.9k",
  },
  {
    rank: 19,
    championId: 134,
    champion: "Syndra",
    games: 17,
    wins: 9,
    losses: 8,
    winRate: "52.9%",
    kda: "3.4",
    avgDamage: "20.2k",
  },
  {
    rank: 20,
    championId: 202,
    champion: "Jhin",
    games: 23,
    wins: 12,
    losses: 11,
    winRate: "52.2%",
    kda: "3.7",
    avgDamage: "26.8k",
  },
];
