// eslint-disable-next-line storybook/no-renderer-packages
import type { Meta, StoryObj } from "@storybook/react";
import { MatchEntry } from "@/components/history/match-entry";
import type { ReducedMatchData } from "@/lib/types";

const meta = {
  title: "Components/MatchEntry",
  component: MatchEntry,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
  argTypes: {
    className: {
      control: "text",
      description: "Additional CSS classes to apply to the component",
    },
  },
} satisfies Meta<typeof MatchEntry>;

export default meta;
type Story = StoryObj<typeof meta>;

const sampleWinningMatch: ReducedMatchData = {
  date: "2025-01-15T23:20:42.993Z",
  gameDuration: 1563,
  gameId: 3102350687,
  gameMode: "CLASSIC",
  gameVersion: "15.10.680.4378",
  participants: [
    // Team 100 (Blue Side) - Winners
    {
      championId: 81, // Ezreal
      championName: "Ezreal",
      participantId: 1,
      role: "adc",
      spells: ["Flash", "Barrier"],
      spellsIds: [4, 21],
      stats: {
        assists: 7,
        champLevel: 14,
        damageDealtToTurrets: 4615,
        damageSelfMitigated: 8148,
        deaths: 1,
        firstBloodKill: false,
        goldEarned: 10506,
        goldSpent: 8733,
        item0: 3078,
        item1: 3042,
        item2: 3111,
        item3: 1036,
        item4: 1036,
        item5: 1036,
        item6: 3363,
        kills: 6,
        largestKillingSpree: 5,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 8297,
        magicalDamageTaken: 5215,
        physicalDamageDealtToChampions: 13510,
        physicalDamageTaken: 8079,
        totalCs: 194,
        totalDamageDealtToChampions: 21807,
        totalDamageTaken: 13713,
        trueDamageDealtToChampions: 0,
        visionScore: 11,
        visionWardsBoughtInGame: 0,
        wardsKilled: 2,
        wardsPlaced: 7,
        win: true,
      },
      summonerId: 1915492,
      summonerName: "Zan",
      tagLine: "BR1",
      teamId: 100,
    },
    {
      championId: 38, // Kassadin
      championName: "Kassadin",
      participantId: 2,
      role: "mid",
      spells: ["Flash", "Teleport"],
      spellsIds: [4, 12],
      stats: {
        assists: 3,
        champLevel: 16,
        damageDealtToTurrets: 6187,
        damageSelfMitigated: 15230,
        deaths: 4,
        firstBloodKill: false,
        goldEarned: 11585,
        goldSpent: 11150,
        item0: 3089,
        item1: 3040,
        item2: 6657,
        item3: 3175,
        item4: 0,
        item5: 0,
        item6: 3364,
        kills: 9,
        largestKillingSpree: 5,
        largestMultiKill: 2,
        magicDamageDealtToChampions: 17560,
        magicalDamageTaken: 7979,
        physicalDamageDealtToChampions: 1683,
        physicalDamageTaken: 12130,
        totalCs: 173,
        totalDamageDealtToChampions: 20031,
        totalDamageTaken: 20798,
        trueDamageDealtToChampions: 788,
        visionScore: 7,
        visionWardsBoughtInGame: 0,
        wardsKilled: 2,
        wardsPlaced: 1,
        win: true,
      },
      summonerId: 2350148,
      summonerName: "Wildscream",
      tagLine: "BR1",
      teamId: 100,
    },
    {
      championId: 5, // XinZhao
      championName: "XinZhao",
      participantId: 3,
      role: "jungle",
      spells: ["Smite", "Flash"],
      spellsIds: [11, 4],
      stats: {
        assists: 8,
        champLevel: 15,
        damageDealtToTurrets: 4842,
        damageSelfMitigated: 18473,
        deaths: 0,
        firstBloodKill: false,
        goldEarned: 10342,
        goldSpent: 8500,
        item0: 6610,
        item1: 6692,
        item2: 2422,
        item3: 3044,
        item4: 1037,
        item5: 0,
        item6: 3340,
        kills: 4,
        largestKillingSpree: 4,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 963,
        magicalDamageTaken: 8536,
        physicalDamageDealtToChampions: 12768,
        physicalDamageTaken: 22246,
        totalCs: 173,
        totalDamageDealtToChampions: 14829,
        totalDamageTaken: 31433,
        trueDamageDealtToChampions: 1097,
        visionScore: 16,
        visionWardsBoughtInGame: 1,
        wardsKilled: 2,
        wardsPlaced: 6,
        win: true,
      },
      summonerId: 23835772,
      summonerName: "loves o RARO",
      tagLine: "5344",
      teamId: 100,
    },
    {
      championId: 58, // Renekton
      championName: "Renekton",
      participantId: 4,
      role: "top",
      spells: ["Teleport", "Flash"],
      spellsIds: [12, 4],
      stats: {
        assists: 3,
        champLevel: 15,
        damageDealtToTurrets: 3138,
        damageSelfMitigated: 13321,
        deaths: 4,
        firstBloodKill: false,
        goldEarned: 9817,
        goldSpent: 7225,
        item0: 6692,
        item1: 3067,
        item2: 0,
        item3: 3044,
        item4: 3111,
        item5: 1054,
        item6: 3363,
        kills: 1,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 1979,
        magicalDamageTaken: 8843,
        physicalDamageDealtToChampions: 8420,
        physicalDamageTaken: 7311,
        totalCs: 205,
        totalDamageDealtToChampions: 10399,
        totalDamageTaken: 17809,
        trueDamageDealtToChampions: 0,
        visionScore: 27,
        visionWardsBoughtInGame: 5,
        wardsKilled: 4,
        wardsPlaced: 13,
        win: true,
      },
      summonerId: 4828128,
      summonerName: "lamarzito",
      tagLine: "br1",
      teamId: 100,
    },
    {
      championId: 267, // Nami
      championName: "Nami",
      participantId: 5,
      role: "support",
      spells: ["Heal", "Flash"],
      spellsIds: [7, 4],
      stats: {
        assists: 16,
        champLevel: 13,
        damageDealtToTurrets: 1376,
        damageSelfMitigated: 3780,
        deaths: 3,
        firstBloodKill: false,
        goldEarned: 7285,
        goldSpent: 6100,
        item0: 3870,
        item1: 1028,
        item2: 4005,
        item3: 4642,
        item4: 3171,
        item5: 2055,
        item6: 3364,
        kills: 0,
        largestKillingSpree: 0,
        largestMultiKill: 0,
        magicDamageDealtToChampions: 6776,
        magicalDamageTaken: 2398,
        physicalDamageDealtToChampions: 516,
        physicalDamageTaken: 4688,
        totalCs: 43,
        totalDamageDealtToChampions: 7292,
        totalDamageTaken: 7188,
        trueDamageDealtToChampions: 0,
        visionScore: 58,
        visionWardsBoughtInGame: 6,
        wardsKilled: 5,
        wardsPlaced: 30,
        win: true,
      },
      summonerId: 18062150,
      summonerName: "Limou",
      tagLine: "LOL",
      teamId: 100,
    },
    // Team 200 (Red Side) - Losers
    {
      championId: 31, // Chogath
      championName: "Chogath",
      participantId: 6,
      role: "top",
      spells: ["Flash", "Teleport"],
      spellsIds: [4, 12],
      stats: {
        assists: 0,
        champLevel: 14,
        damageDealtToTurrets: 3321,
        damageSelfMitigated: 26585,
        deaths: 2,
        firstBloodKill: true,
        goldEarned: 9720,
        goldSpent: 8975,
        item0: 1054,
        item1: 3076,
        item2: 3084,
        item3: 3068,
        item4: 3047,
        item5: 1031,
        item6: 3340,
        kills: 5,
        largestKillingSpree: 4,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 9057,
        magicalDamageTaken: 8426,
        physicalDamageDealtToChampions: 4464,
        physicalDamageTaken: 14980,
        totalCs: 165,
        totalDamageDealtToChampions: 15249,
        totalDamageTaken: 23957,
        trueDamageDealtToChampions: 1727,
        visionScore: 20,
        visionWardsBoughtInGame: 1,
        wardsKilled: 3,
        wardsPlaced: 10,
        win: false,
      },
      summonerId: 996728,
      summonerName: "Andrey de Graves",
      tagLine: "BR1",
      teamId: 200,
    },
    {
      championId: 61, // Orianna
      championName: "Orianna",
      participantId: 7,
      role: "mid",
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 4,
        champLevel: 12,
        damageDealtToTurrets: 0,
        damageSelfMitigated: 7193,
        deaths: 6,
        firstBloodKill: false,
        goldEarned: 6987,
        goldSpent: 6550,
        item0: 1056,
        item1: 3040,
        item2: 3020,
        item3: 1052,
        item4: 3145,
        item5: 1027,
        item6: 3364,
        kills: 2,
        largestKillingSpree: 2,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 9220,
        magicalDamageTaken: 6212,
        physicalDamageDealtToChampions: 1946,
        physicalDamageTaken: 5748,
        totalCs: 120,
        totalDamageDealtToChampions: 11452,
        totalDamageTaken: 12347,
        trueDamageDealtToChampions: 285,
        visionScore: 12,
        visionWardsBoughtInGame: 2,
        wardsKilled: 2,
        wardsPlaced: 5,
        win: false,
      },
      summonerId: 996727,
      summonerName: "Mono Bola",
      tagLine: "BR24",
      teamId: 200,
    },
    {
      championId: 111, // Nautilus
      championName: "Nautilus",
      participantId: 8,
      role: "support",
      spells: ["Flash", "Ignite"],
      spellsIds: [4, 14],
      stats: {
        assists: 4,
        champLevel: 11,
        damageDealtToTurrets: 931,
        damageSelfMitigated: 29077,
        deaths: 4,
        firstBloodKill: false,
        goldEarned: 6381,
        goldSpent: 6275,
        item0: 3869,
        item1: 3190,
        item2: 3047,
        item3: 3109,
        item4: 0,
        item5: 0,
        item6: 3364,
        kills: 2,
        largestKillingSpree: 2,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 3800,
        magicalDamageTaken: 5667,
        physicalDamageDealtToChampions: 1258,
        physicalDamageTaken: 9930,
        totalCs: 33,
        totalDamageDealtToChampions: 5819,
        totalDamageTaken: 15823,
        trueDamageDealtToChampions: 761,
        visionScore: 57,
        visionWardsBoughtInGame: 1,
        wardsKilled: 10,
        wardsPlaced: 19,
        win: false,
      },
      summonerId: 3552895,
      summonerName: "Welligton",
      tagLine: "br1",
      teamId: 200,
    },
    {
      championId: 498, // Xayah
      championName: "Xayah",
      participantId: 9,
      role: "adc",
      spells: ["Flash", "Barrier"],
      spellsIds: [4, 21],
      stats: {
        assists: 5,
        champLevel: 12,
        damageDealtToTurrets: 3599,
        damageSelfMitigated: 6204,
        deaths: 4,
        firstBloodKill: false,
        goldEarned: 9872,
        goldSpent: 9200,
        item0: 1055,
        item1: 3032,
        item2: 3006,
        item3: 6675,
        item4: 1038,
        item5: 1037,
        item6: 3363,
        kills: 2,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 207,
        magicalDamageTaken: 8769,
        physicalDamageDealtToChampions: 14701,
        physicalDamageTaken: 6235,
        totalCs: 212,
        totalDamageDealtToChampions: 14909,
        totalDamageTaken: 15324,
        trueDamageDealtToChampions: 0,
        visionScore: 6,
        visionWardsBoughtInGame: 1,
        wardsKilled: 0,
        wardsPlaced: 6,
        win: false,
      },
      summonerId: 401897,
      summonerName: "Twino3x",
      tagLine: "BR1",
      teamId: 200,
    },
    {
      championId: 245, // Ekko
      championName: "Ekko",
      participantId: 10,
      role: "jungle",
      spells: ["Smite", "Flash"],
      spellsIds: [11, 4],
      stats: {
        assists: 4,
        champLevel: 12,
        damageDealtToTurrets: 562,
        damageSelfMitigated: 18861,
        deaths: 4,
        firstBloodKill: false,
        goldEarned: 7847,
        goldSpent: 7700,
        item0: 4645,
        item1: 3100,
        item2: 0,
        item3: 3020,
        item4: 0,
        item5: 0,
        item6: 3364,
        kills: 1,
        largestKillingSpree: 0,
        largestMultiKill: 1,
        magicDamageDealtToChampions: 7824,
        magicalDamageTaken: 10564,
        physicalDamageDealtToChampions: 1028,
        physicalDamageTaken: 19263,
        totalCs: 143,
        totalDamageDealtToChampions: 9593,
        totalDamageTaken: 30231,
        trueDamageDealtToChampions: 740,
        visionScore: 14,
        visionWardsBoughtInGame: 4,
        wardsKilled: 4,
        wardsPlaced: 4,
        win: false,
      },
      summonerId: 16591425,
      summonerName: "Vhex",
      tagLine: "br1",
      teamId: 200,
    },
  ],
  teams: [
    {
      bans: [
        { championId: 420, pickTurn: 1 },
        { championId: 104, pickTurn: 3 },
        { championId: 516, pickTurn: 5 },
        { championId: 99, pickTurn: 2 },
        { championId: 122, pickTurn: 4 },
      ],
      baronKills: 0,
      dominionVictoryScore: 0,
      dragonKills: 3,
      firstBaron: false,
      firstBlood: false,
      firstDargon: true,
      firstInhibitor: true,
      firstTower: true,
      hordeKills: 0,
      inhibitorKills: 2,
      riftHeraldKills: 1,
      teamId: 100,
      towerKills: 7,
      vilemawKills: 0,
      win: "Win",
    },
    {
      bans: [
        { championId: 22, pickTurn: 2 },
        { championId: 121, pickTurn: 4 },
        { championId: 80, pickTurn: 6 },
        { championId: 875, pickTurn: 1 },
        { championId: 83, pickTurn: 3 },
      ],
      baronKills: 0,
      dominionVictoryScore: 0,
      dragonKills: 1,
      firstBaron: false,
      firstBlood: true,
      firstDargon: false,
      firstInhibitor: false,
      firstTower: false,
      hordeKills: 3,
      inhibitorKills: 0,
      riftHeraldKills: 0,
      teamId: 200,
      towerKills: 2,
      vilemawKills: 0,
      win: "Fail",
    },
  ],
};

const shortMatch: ReducedMatchData = {
  ...sampleWinningMatch,
  gameDuration: 892, // ~15 minutes
  date: "2025-01-16T14:30:15.123Z",
  gameMode: "ARAM",
};

export const StandardMatch: Story = {
  args: {
    match: sampleWinningMatch,
  },
};

export const ShortMatch: Story = {
  args: {
    match: shortMatch,
  },
};

export const WithCustomClassName: Story = {
  args: {
    match: sampleWinningMatch,
    className: "max-w-4xl",
  },
};

export const Mobile: Story = {
  args: {
    match: sampleWinningMatch,
  },
  render: () => (
    <div className="w-full max-w-full">
      <MatchEntry match={sampleWinningMatch} />
    </div>
  ),
  globals: {
    viewport: { value: "mobile1", isRotated: false },
  },
};

export const Tablet: Story = {
  args: {
    match: sampleWinningMatch,
  },
  render: () => (
    <div style={{ width: "768px", maxWidth: "768px" }}>
      <MatchEntry match={sampleWinningMatch} />
    </div>
  ),
  globals: {
    viewport: { value: "tablet", isRotated: false },
  },
};

export const Desktop: Story = {
  args: {
    match: sampleWinningMatch,
  },
  render: () => (
    <div style={{ width: "1280px", maxWidth: "1280px" }}>
      <MatchEntry match={sampleWinningMatch} />
    </div>
  ),
  parameters: {
    layout: "padded",
  },
  globals: {
    viewport: { value: "desktop", isRotated: false },
  },
};

export const MatchHistory: Story = {
  args: {
    match: sampleWinningMatch,
  },
  render: () => (
    <div className="space-y-4 max-w-4xl">
      <MatchEntry match={sampleWinningMatch} />
      <MatchEntry match={shortMatch} />
      <MatchEntry
        match={{ ...sampleWinningMatch, date: "2025-01-14T18:45:30.456Z" }}
      />
    </div>
  ),
};
